import express from "express";
import { auth, authorizeRole } from "../../middlewares/authMiddleware.js";
import {
  enable2FA,
  verify2FA,
  verify2FAafterlogin,
  verifyRecoveryCode,
  disable2FA,
} from "../../modules/admin/controllers/googleAuthentication.js";

const router = express.Router();

/**
 * @swagger
 * tags:
 *   name: 2FA Authentication
 *   description: Google Authenticator-based Two-Factor Authentication (TOTP) endpoints
 */

/**
 * @swagger
 * /api/admin/2fa/enable:
 *   post:
 *     summary: Initiate 2FA setup
 *     description: >
 *       Generates a TOTP secret and returns a QR code (base64 data URL) for the
 *       authenticated admin to scan with Google Authenticator. The secret is stored
 *       temporarily until it is confirmed via the `/verify` endpoint.
 *     tags: [2FA Authentication]
 *     security:
 *       - bearerAuth: []
 *     responses:
 *       200:
 *         description: 2FA setup initiated successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 status:
 *                   type: integer
 *                   example: 1
 *                 message:
 *                   type: string
 *                   example: success_2fa_setup_started
 *                 data:
 *                   type: object
 *                   properties:
 *                     qrCode:
 *                       type: string
 *                       description: Base64 encoded QR code image (data URL)
 *                       example: "data:image/png;base64,iVBORw0KGgo..."
 *                     otpauthUrl:
 *                       type: string
 *                       description: OTP Auth URI for manual entry
 *                       example: "otpauth://totp/ContentHub:admin@example.com?secret=JBSWY3DPEHPK3PXP&issuer=ContentHub"
 *                     secret:
 *                       type: string
 *                       description: Base32-encoded TOTP secret (for manual entry)
 *                       example: "JBSWY3DPEHPK3PXP"
 *       400:
 *         description: 2FA is already enabled for this user
 *       401:
 *         description: Unauthorized – missing or invalid token
 *       500:
 *         description: Internal server error
 */
router.post("/enable", auth, authorizeRole("admin"), enable2FA);

/**
 * @swagger
 * /api/admin/2fa/verify:
 *   post:
 *     summary: Verify OTP and activate 2FA
 *     description: >
 *       Validates the OTP generated by the authenticator app against the temporary
 *       secret. On success, 2FA is permanently enabled and recovery codes are returned.
 *       These recovery codes should be saved by the user as they cannot be retrieved again.
 *     tags: [2FA Authentication]
 *     security:
 *       - bearerAuth: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - otp
 *             properties:
 *               otp:
 *                 type: string
 *                 description: 6-digit TOTP code from Google Authenticator
 *                 example: "123456"
 *     responses:
 *       200:
 *         description: 2FA successfully enabled – recovery codes returned
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 status:
 *                   type: integer
 *                   example: 1
 *                 message:
 *                   type: string
 *                   example: success_2fa_enabled
 *                 data:
 *                   type: object
 *                   properties:
 *                     recoveryCodes:
 *                       type: array
 *                       description: One-time use backup recovery codes
 *                       items:
 *                         type: string
 *                       example: ["ABCD-1234", "EFGH-5678"]
 *       400:
 *         description: OTP not provided or 2FA setup was not initiated
 *       401:
 *         description: Invalid or expired OTP
 *       500:
 *         description: Internal server error
 */
router.post("/verify", auth, authorizeRole("admin"), verify2FA);

/**
 * @swagger
 * /api/admin/2fa/disable:
 *   post:
 *     summary: Disable 2FA for the authenticated admin
 *     description: >
 *       Disables Two-Factor Authentication for the currently logged-in admin.
 *       Requires the admin's current password for confirmation. All stored recovery
 *       codes are also deleted upon successful disablement.
 *     tags: [2FA Authentication]
 *     security:
 *       - bearerAuth: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - password
 *             properties:
 *               password:
 *                 type: string
 *                 format: password
 *                 description: The admin's current account password
 *                 example: "MySecureP@ssword123"
 *     responses:
 *       200:
 *         description: 2FA disabled successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 status:
 *                   type: integer
 *                   example: 1
 *                 message:
 *                   type: string
 *                   example: success_updated
 *       400:
 *         description: Password not provided
 *       401:
 *         description: Invalid password or unauthorized
 *       404:
 *         description: User not found
 *       500:
 *         description: Internal server error
 */
router.post("/disable", auth, authorizeRole("admin"), disable2FA);

/**
 * @swagger
 * /api/admin/2fa/verify-after-login:
 *   post:
 *     summary: Complete login by verifying TOTP code (post-login 2FA step)
 *     description: >
 *       Called during the login flow when the user has 2FA enabled. After the initial
 *       username/password check, a temporary 2FA token is issued. This endpoint accepts
 *       that token along with the current OTP from the authenticator app and returns
 *       the final access and refresh tokens on success.
 *     tags: [2FA Authentication]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - otp
 *               - tempToken
 *             properties:
 *               otp:
 *                 type: string
 *                 description: 6-digit TOTP code from the authenticator app
 *                 example: "654321"
 *               tempToken:
 *                 type: string
 *                 description: Temporary JWT issued after the initial login step (type '2fa')
 *                 example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
 *     responses:
 *       200:
 *         description: 2FA verified – full session tokens returned
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 status:
 *                   type: integer
 *                   example: 1
 *                 message:
 *                   type: string
 *                   example: success_2fa_login
 *                 data:
 *                   type: object
 *                   properties:
 *                     user:
 *                       type: object
 *                       description: Authenticated user's profile (sensitive fields excluded)
 *                     tokens:
 *                       type: object
 *                       properties:
 *                         accessToken:
 *                           type: string
 *                           example: "eyJhbGci..."
 *                         refreshToken:
 *                           type: string
 *                           example: "eyJhbGci..."
 *       400:
 *         description: OTP or tempToken not provided
 *       401:
 *         description: Invalid or expired temp token / invalid OTP
 *       404:
 *         description: User not found
 *       500:
 *         description: Internal server error
 */
router.post("/verify-after-login", verify2FAafterlogin);

/**
 * @swagger
 * /api/admin/2fa/verify-recovery-code:
 *   post:
 *     summary: Login using a 2FA recovery code
 *     description: >
 *       Allows an admin to bypass the TOTP step during login by providing one of their
 *       pre-generated recovery codes. Each recovery code can only be used once. On success,
 *       the code is marked as used and final session tokens are returned.
 *     tags: [2FA Authentication]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - code
 *               - tempToken
 *             properties:
 *               code:
 *                 type: string
 *                 description: One of the plaintext recovery codes issued when 2FA was enabled
 *                 example: "ABCD-1234"
 *               tempToken:
 *                 type: string
 *                 description: Temporary JWT issued after the initial login step (type '2fa')
 *                 example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
 *     responses:
 *       200:
 *         description: Recovery code verified – full session tokens returned
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 status:
 *                   type: integer
 *                   example: 1
 *                 message:
 *                   type: string
 *                   example: success_recovery_code_login
 *                 data:
 *                   type: object
 *                   properties:
 *                     user:
 *                       type: object
 *                       description: Authenticated user's profile (sensitive fields excluded)
 *                     tokens:
 *                       type: object
 *                       properties:
 *                         accessToken:
 *                           type: string
 *                           example: "eyJhbGci..."
 *                         refreshToken:
 *                           type: string
 *                           example: "eyJhbGci..."
 *       400:
 *         description: Code or tempToken not provided
 *       401:
 *         description: Invalid temp token
 *       404:
 *         description: User not found
 *       422:
 *         description: Invalid or already-used recovery code
 *       500:
 *         description: Internal server error
 */
router.post("/verify-recovery-code", verifyRecoveryCode);

export default router;

